### PR TITLE
Minor performance improvement:

### PR DESCRIPTION
**Pull request by Gnouc**
- Revise _short_url, using bash builtin string substitution
 - Adding _has_command for shorter checking
 - Fix some quote issues

### CODE REVIEW

**Comment by Gnouc** [comment]
A consideration option for performance improvement can be using `LC_ALL=C`. But I'm not sure about the input data so I decide to make it in future.

Also note that on GNU systems with UTF-8 locales, `sort -u` does not report unique lines but the first from sequence of lines which sort the same:
```
$ printf '%b\n' '\U2460' '\U2461' | LC_ALL=en_US.utf8 sort -u
①
```

**Comment by icy** [comment]
> Revise _short_url, using bash builtin string substitution
I often use `sed`, mostly because it's readable (esp. when using `sed -r` when possible.)

> Also note that on GNU systems with UTF-8 locales, sort -u does not report unique lines but the first from sequence of lines which sort the same:

Yah I know. Let's keep that simple, though ;)

**Comment by icy** [comment]
Thanks a lot for your contribution, @Gnouc !

**Comment by Gnouc** [comment]
> I often use sed, mostly because it's readable (esp. when using sed -r when possible.)

You should use undocumented `sed -E` with GNU sed (which equivalent to `sed -r`). `-E` option works in BSD sed, too and [are going to be standard in next POSIX](http://austingroupbugs.net/view.php?id=528).

**Comment by icy** [comment]
Very valuable information :)

**Pull request merged**
